export const RecordTypes={
    FETCH_ALL_CURRENCY_DATA:'FETCH_CURRENCY_DATA',
    FETCH_SAVED_CURRENCY_DATA:'FETCH_SAVED_CURRENCY_DATA',
    POST_SAVED_CURRENCY_DATA:'UPDATE_SAVED_CURRENCY_DATA',
    DELETE_SAVED_CURRENCY_DATA:'DELETE_CURRENCY_DATA',
}